WE.blockNames = {
    { "stone", "rock" },
    { "grass" },
    { "dirt" },
    { "cobblestone", "cobble" },
    { "wood", "woodplank", "plank", "woodplanks", "planks" },
    { "sapling", "seedling" },
    { "adminium", "bedrock" },
    { "water_(stationary)", "water", "waterstationary", "stationarywater", "stillwater" },
    { "watermoving", "movingwater", "flowingwater", "waterflowing" },
    { "lavamoving", "movinglava", "flowinglava", "lavaflowing" },
    { "lava_(stationary)", "lava", "lavastationary", "stationarylava", "stilllava" },
    { "sand", "redsand", "red_sand" },
    { "gravel" },
    { "gold_ore", "goldore" },
    { "iron_ore", "ironore" },
    { "coal_ore", "coalore" },
    { "log", "tree", "pine", "oak", "birch", "jungle" },
    { "leaves", "leaf" },
    { "sponge" },
    { "glass" },
    { "lapis_lazuli_ore", "lapislazuliore", "blueore", "lapisore" },
    { "lapis_lazuli", "lapislazuli", "lapislazuliblock", "bluerock", "lapisblock" },
    { "dispenser" },
    { "sandstone" },
    { "note_block", "musicblock", "noteblock", "note", "music", "instrument" },
    { "bed" },
    { "poweredrail", "boosterrail", "poweredtrack", "boostertrack", "booster" },
    { "detector_rail", "detectorrail", "detector" },
    { "sticky_piston", "stickypiston" },
    { "web", "spiderweb" },
    { "tall_grass", "long_grass", "longgrass", "tallgrass" },
    { "deadbush", "shrub", "deadshrub", "tumbleweed" },
    { "piston" },
    { "piston_extension", "pistonextendsion", "pistonhead" },
    { "cloth", "wool" },
    { "piston_moving_piece", "movingpiston" },
    { "yellow_flower", "yellowflower", "flower" },
    { "red_rose", "redflower", "redrose", "rose" },
    { "brown_mushroom", "brownmushroom", "mushroom" },
    { "red_mushroom", "redmushroom" },
    { "gold_block", "gold", "goldblock" },
    { "iron_block", "iron", "ironblock" },
    { "double_step", "doubleslab", "doublestoneslab", "doublestep" },
    { "slab", "stoneslab", "step", "halfstep" },
    { "brick", "brickblock" },
    { "tnt", "c4", "explosive" },
    { "bookshelf", "bookshelves", "bookcase", "bookcases" },
    { "cobblestone_(mossy)", "mossycobblestone", "mossstone" },
    { "obsidian" },
    { "torch", "light", "candle" },
    { "fire", "flame", "flames" },
    { "mob_spawner", "mobspawner", "spawner" },
    { "wooden_stairs", "woodstair", "woodstairs", "woodenstair", "woodenstairs" },
    { "chest", "storage", "storagechest" },
    { "redstone_wire", "redstone", "redstoneblock" },
    { "diamond_ore", "diamondore" },
    { "diamond_block", "diamond", "diamondblock" },
    { "workbench", "table", "craftingtable", "crafting" },
    { "crops", "crop", "plant", "plants" },
    { "soil", "farmland" },
    { "furnace" },
    { "furnace_(burning)", "burningfurnace", "litfurnace" },
    { "sign_post", "sign", "signpost" },
    { "wooden_door", "wooddoor", "woodendoor", "door" },
    { "ladder" },
    { "minecart_tracks", "track", "tracks", "minecrattrack", "minecarttracks", "rails", "rail" },
    { "cobblestone_stairs", "cobblestonestair", "cobblestonestairs", "cobblestair", "cobblestairs" },
    { "wall_sign", "wallsign" },
    { "lever", "switch", "stonelever", "stoneswitch" },
    { "stone_pressure_plate", "stonepressureplate", "stoneplate" },
    { "iron_door", "irondoor" },
    { "wooden_pressure_plate", "woodpressureplate", "woodplate", "woodenpressureplate", "woodenplate", "plate", "pressureplate" },
    { "redstone_ore", "redstoneore" },
    { "glowing_redstone_ore", "glowingredstoneore" },
    { "redstone_torch_(off)", "redstonetorchoff", "rstorchoff" },
    { "redstone_torch_(on)", "redstonetorch", "redstonetorchon", "rstorchon", "redtorch" },
    { "stone_button", "stonebutton", "button" },
    { "snow", "snow_layer" },
    { "ice" },
    { "snow_block", "snowblock" },
    { "cactus", "cacti" },
    { "clay" },
    { "reed", "cane", "sugarcane", "sugarcanes" },
    { "jukebox", "stereo", "recordplayer" },
    { "fence", "fence" },
    { "pumpkin" },
    { "redmossycobblestone", "redcobblestone", "redmosstone", "redcobble", "netherstone", "netherrack", "nether", "hellstone" },
    { "soul_sand", "slowmud", "mud", "soulsand", "hellmud" },
    { "glowstone", "brittlegold", "lightstone", "brimstone", "australium" },
    { "portal", "portal" },
    { "pumpkin_(on)", "pumpkinlighted", "pumpkinon", "litpumpkin", "jackolantern" },
    { "cake", "cakeblock" },
    { "redstone_repeater_(off)", "diodeoff", "redstonerepeater", "repeateroff", "delayeroff" },
    { "redstone_repeater_(on)", "diodeon", "redstonerepeateron", "repeateron", "delayeron" },
    { "stained_glass", "stainedglass" },
    { "trap_door", "trapdoor", "hatch", "floordoor" },
    { "silverfish_block", "silverfish", "silver" },
    { "stone_brick", "stonebrick", "sbrick", "smoothstonebrick" },
    { "red_mushroom_cap", "giantmushroomred", "redgiantmushroom", "redmushroomcap" },
    { "brown_mushroom_cap", "giantmushroombrown", "browngiantmushoom", "brownmushroomcap" },
    { "iron_bars", "ironbars", "ironfence" },
    { "glass_pane", "window", "glasspane", "glasswindow" },
    { "melon_(block)", "melonblock" },
    { "pumpkin_stem", "pumpkinstem" },
    { "melon_stem", "melonstem" },
    { "vine", "vines", "creepers" },
    { "fence_gate", "fencegate", "gate" },
    { "brick_stairs", "brickstairs", "bricksteps" },
    { "stone_brick_stairs", "stonebrickstairs", "smoothstonebrickstairs" },
    { "mycelium", "fungus", "mycel" },
    { "lily_pad", "lilypad", "waterlily" },
    { "nether_brick", "netherbrick" },
    { "nether_brick_fence", "netherbrickfence", "netherfence" },
    { "nether_brick_stairs", "netherbrickstairs", "netherbricksteps", "netherstairs", "nethersteps" },
    { "nether_wart", "netherwart", "netherstalk" },
    { "enchantment_table", "enchantmenttable", "enchanttable" },
    { "brewing_stand", "brewingstand" },
    { "cauldron" },
    { "end_portal", "endportal", "blackstuff", "airportal", "weirdblackstuff" },
    { "end_portal_frame", "endportalframe", "airportalframe", "crystalblock" },
    { "end_stone", "endstone", "enderstone", "endersand" },
    { "dragon_egg", "dragonegg", "dragons" },
    { "redstone_lamp_(off)", "redstonelamp", "redstonelampoff", "rslamp", "rslampoff", "rsglow", "rsglowoff" },
    { "redstone_lamp_(on)", "redstonelampon", "rslampon", "rsglowon" },
    { "double_wood_step", "doublewoodslab", "doublewoodstep" },
    { "wood_step", "woodenslab", "woodslab", "woodstep", "woodhalfstep" },
    { "cocoa_plant", "cocoplant", "cocoaplant" },
    { "sandstone_stairs", "sandstairs", "sandstonestairs" },
    { "emerald_ore", "emeraldore" },
    { "ender_chest", "enderchest" },
    { "tripwire_hook", "tripwirehook" },
    { "tripwire", "string" },
    { "emerald_block", "emeraldblock", "emerald" },
    { "spruce_wood_stairs", "sprucestairs", "sprucewoodstairs" },
    { "birch_wood_stairs", "birchstairs", "birchwoodstairs" },
    { "jungle_wood_stairs", "junglestairs", "junglewoodstairs" },
    { "command_block", "commandblock", "cmdblock", "command", "cmd" },
    { "beacon", "beaconblock" },
    { "cobblestone_wall", "cobblestonewall", "cobblewall" },
    { "flower_pot", "flowerpot", "plantpot", "pot" },
    { "carrots", "carrotsplant", "carrotsblock" },
    { "potatoes", "potatoesblock" },
    { "wooden_button", "woodbutton", "woodenbutton" },
    { "head", "skull" },
    { "anvil", "blacksmith" },
    { "trapped_chest", "trappedchest", "redstonechest" },
    { "weighted_pressure_plate_(light)", "lightpressureplate" },
    { "weighted_pressure_plate_(heavy)", "heavypressureplate" },
    { "redstone_comparator_(inactive)", "redstonecomparator", "comparator" },
    { "redstone_comparator_(active)", "redstonecomparatoron", "comparatoron" },
    { "daylight_sensor", "daylightsensor", "lightsensor", "daylightdetector" },
    { "block_of_redstone", "redstoneblock", "blockofredstone" },
    { "nether_quartz_ore", "quartzore", "netherquartzore" },
    { "hopper" },
    { "block_of_quartz", "quartzblock", "quartz" },
    { "quartz_stairs", "quartzstairs" },
    { "activator_rail", "activatorrail", "tntrail", "activatortrack" },
    { "dropper" },
    { "stained_clay", "stainedclay", "stainedhardenedclay" },
    { "stained_glass_pane", "stainedglasspane" },
    { "leaves2", "acacialeaves", "darkoakleaves" },
    { "log2", "acacia", "darkoak" },
    { "acacia_wood_stairs", "acaciawoodstairs", "acaciastairs" },
    { "dark_oak_wood_stairs", "darkoakwoodstairs", "darkoakstairs" },
    [165] = { "slimeblock", "slime_block" },
    [170] = { "hay_block", "hayblock", "haybale", "wheatbale" },
    [171] = { "carpet", "carpet" },
    [172] = { "hardened_clay", "hardenedclay", "hardclay" },
    [173] = { "block_of_coal", "coalblock", "blockofcoal" },
    [174] = { "packed_ice", "packedice", "hardice" },
    [175] = { "large_flowers", "largeflowers", "doubleflowers" },
    [176] = { "large_flowers", "largeflowers", "doubleflowers" },
    [0] = { "air" }
}
return true
